### ISSUE TITLE
Reduce global app font size

### ISSUE THREAD

**Issue by luxferoo** [mardtendebakker/nsk#273]

**Comment by mardtendebakker** [comment]
I think the font size should be editable in a template. but the white spaces are too much.

i made a sample to show what i mean. 
Also the map in logistics is great but i think the pop up it must be wider to be able to see the pickups clearly :)


![Image](https://github.com/mardtendebakker/nsk/assets/126237209/f8198ac8-1d37-4817-aff2-1afdebb47e32)

**Comment by luxferoo** [comment]
Hi mardten I'll handle spaces I noticed that but it was too late haha. But I don't think it's possible to be efficient with a font administration pannel it's too overkill and any browser allows to zoom in/out (I do that for facebook for example)

**Comment by mardtendebakker** [comment]
The manage theme in figma is able to set color and logo. Is it not possible to add fontsize to choose between 10 and 14pt or 85%-115%?It should be a simple thing to do in the CSS? Not everybody know about crtl + scroll😊   Van: imam harirVerzonden: vrijdag 7 juli 2023 11:55Aan: mardtendebakker/nskCC: mardtendebakker; CommentOnderwerp: Re: [mardtendebakker/nsk] Reduce global app font size (Issue #273) Hi mardten I'll handle spaces I noticed that but it was too late haha. But I don't think it's possible to be efficient with a font administration pannel it's too overkill and any browser allows to zoom in/out (I do that for facebook for example)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
