### ISSUE TITLE
print pricecards

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#500]

**Comment by mardtendebakker** [comment]
when select attributes there is a price per atrribute.
But i am missing the total price in the product and pricecard.
1666258266
Also if you look at the pricecard the rows are irregular in color.

**Comment by shayank** [comment]
Currently, the price that we can see in the pricecard is Retail price.
In this case (1666258266) Retail price is 0.
should we see the List price in pricecard?
I am asking because in old Nexxus it was Retail price.
e.g. 
1666258266
http://demo.nexxus.eco/nsk/product/bulkedit?index_bulk_edit_form%5Baction%5D=pricecards&index_bulk_edit_form%5Bindex%5D%5B%5D=19

**Comment by mardtendebakker** [comment]
Hi ShayanGood question.So the listprice is the price when adding up all the attributes.That should be the factory product price. When we value the product diffently because of damage for example, then we need to be able to change that price. Let’s say the current Price field is and stays Retail.Then the list price should be visible underneath it as a guideline.None of these prices are currently visible especially not in the salesorder.Neither list, Retail or salesprice   Verzonden vanuit Mail voor Windows Van: Shayan KaramiVerzonden: dinsdag 12 september 2023 14:53Aan: mardtendebakker/nskCC: mardtendebakker; CommentOnderwerp: Re: [mardtendebakker/nsk] print pricecards (Issue #500) Currently, the price that we can see in the pricecard is Retail price.In this case (1666258266) Retail price is 0.should we see the List price in pricecard?I am asking because in old Nexxus it was Retail price.e.g.1666258266http://demo.nexxus.eco/nsk/product/bulkedit?index_bulk_edit_form%5Baction%5D=pricecards&index_bulk_edit_form%5Bindex%5D%5B%5D=19—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by mardtendebakker** [comment]
I added the Retail price manually which is fine if i can see the list price in the product also  1666258266Acer 730 series (split 38)Televisiestraat 2E€50.001----1 Salesorder1666258266Acer 730 series (split 38)Laptop----   Verzonden vanuit Mail voor Windows Van: Shayan KaramiVerzonden: dinsdag 12 september 2023 14:53Aan: mardtendebakker/nskCC: mardtendebakker; CommentOnderwerp: Re: [mardtendebakker/nsk] print pricecards (Issue #500) Currently, the price that we can see in the pricecard is Retail price.In this case (1666258266) Retail price is 0.should we see the List price in pricecard?I am asking because in old Nexxus it was Retail price.e.g.1666258266http://demo.nexxus.eco/nsk/product/bulkedit?index_bulk_edit_form%5Baction%5D=pricecards&index_bulk_edit_form%5Bindex%5D%5B%5D=19—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
